#+TITLE: About me

I am a PhD student studying urban planning at the University of
Washington in Seattle. My current research focusses on how cities
collect and process information. This includes privacy (how can cities
avoid becoming panopticons?) as well as how to make quantitative
aspects of planning more transparent, reproducible, and inclusive.
Other interests include transportation planning, especially for
bicyclists and pedestrians. Immediately prior to starting my PhD, I
worked in the transportation modeling team at the [[http://www.psrc.org][Puget Sound Regional
Council]].

Before converting my long-term passion for bicycle and pedestrian
advocacy into a career in urban planning, I worked on Unix/Network
systems and security in the United States and New Zealand. As a
holdover from this experience, I retain a love of command lines, and a
distrust of analyses that are not automated and repeatable. My
experience in New Zealand left me with an insatiable appetite for
[[https://en.wikipedia.org/wiki/Acca_sellowiana][feijoas]] and a desire to someday return.
